"""empty message

Revision ID: 8ba4f041eb86
Revises: c1786e856ddc
Create Date: 2023-11-08 15:35:56.415780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba4f041eb86'
down_revision = 'c1786e856ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
